### ISSUE TITLE
Why are the macros documented as a GitHub wiki?

### ISSUE THREAD

**Issue by jplatte** [Peternator7/strum#115]
This means that you can't just open a PR improving (this part of) the docs, or easily access the docs for an older version. I think there were some issues with documenting proc macros in rustdoc in the past, but they have long been fixed. Could the docs be moved out of the Wiki?

**Comment by Peternator7** [comment]
The annoying thing about documenting them with rust-docs was that I needed to publish a new version to just update the docs which slowed down the process. I'm not opposed to switching them back, but it's not a particularly high priority.

**Comment by mike-kfed** [comment]
would you accept a pull-request for moving docs to the source? Because e.g. the wiki entry for EnumVariantNames does not match reality. In the first paragraph it references the variants() method, which no longer exists. The clap example code uses the constant but does not import from strum_macros. The structopt example is using old structopt raw and the old variants() method. If those code examples were doctests they would be in working order, right now none of those even compile. Other option: they could be example code, in the examples folder.
Anyways I'd be happy to help with any of that, as this will make it easier for new users starting to use this crate.

**Comment by Peternator7** [comment]
Hi @mike-kfed, yes I'd be happy to accept a PR if you put one together :)

**Comment by mike-kfed** [comment]
putting it in the strum docs is not as easy as expected, looking at rust-lang/cargo#2760 documenting code from examples is not included in the normal docs. This allows following options:

1. we tell people in the docs to check the examples folder where a README explains the examples.
1. we use a similar script as f3 (see cargo-doc issue) to create a "examples module" to have code in the html docs
1. we actually put code docs into the strum_macros crate and only additional examples in examples folder

p.s. I started with option 1 first, see here https://github.com/mike-kfed/strum/tree/wiki_to_examples/strum/examples as this will be the most straight forward, given that the examples are not really tests. `cargo build --examples` shows at least if they compile ;)

please let me know which option you prefer and I'll continue working on this :)

**Comment by jplatte** [comment]
> we tell people in the docs to check the examples folder where a README explains the examples.

This still requires jumping around, even more if you want to look at the examples for an older version :slightly_frowning_face: 

I'd much prefer doctests (3).

**Comment by mike-kfed** [comment]
doctests would work fine except for the structopt example. To allow for any example to be in the docs we'd need to run the copy script that f3 does (which creates an examples module in src/ that only holds documentation) = solution A.
solution B - rewrite the examples to be doc-tests (=remove the structopt example*).

keeping the current examples dir works too, you just need to git-tag the versions and link correctly in the docs. yes still jumping around but also a better way to go than the current wiki solution.

(*) structopt doesn't make it through your CI right now (needs rustc >=1.36). Changing it to be a comment only keeps the problem alive that the example-code might not be compatible with structopt and nobody notices since it is never compiled and therefore checked.

**Comment by mike-kfed** [comment]
one more thing, docs.rs has the full source per release available, you can actually link to the examples fine, e.g. for warp https://docs.rs/crate/warp/0.2.5/source/examples/ maybe the examples dir option is good enough.

**Comment by jplatte** [comment]
Okay so about how to document these: There is two ways. Either you document the macros directly such that strum_macros also has this documentation. That requires adding a dev-dependency from strum_macros to strum (which isn't very unusual though). Then you can just add a regular doc comment to the derive functions in strum_macros.

The other solution would be to update `pub use strum_macros::*;` to

```rust
/// docs for AsRefStr
#[cfg(feature = "derive")]
pub use strum_macros::AsRefStr;

/// docs for EnumString
#[cfg(feature = "derive")]
pub use strum_macros::EnumString;

// ...
```

In any case the `#[doc(hidden)]` attribute has to be removed from the macro re-exports [here](https://github.com/Peternator7/strum/blob/master/strum/src/lib.rs#L207).

It probably makes sense to also document that the derive macros require a cargo feature by update `Cargo.toml`:

```toml
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
```

and `lib.rs`:

```rust
// crate attributes near the top
#![cfg_attr(docsrs, feature(doc_cfg))]

// on the re-export(s)
#[cfg_attr(docsrs, doc(cfg(feature = "derive")))]
```

SQLx is a good example of what this [looks like](https://docs.rs/sqlx/0.3.5/sqlx/mysql/index.html) in rustdoc.

**Comment by mike-kfed** [comment]
thanks for your help! I'll follow the update `pub use strum_macros::*;` route to separate `use`s and document them, if nobody objects to that. This way docs stay within strum which seems to be the preferred way anyhow.

**Comment by Peternator7** [comment]
Thanks for the help both of you. I would agree that using doctests is preferable to examples, and we can add additional examples as needed.

I would probably prefer the documentation be on the `strum_macros` and then have those docs re-exported into strum proper, but I'm not familiar off the top of my head with whether that's doable or not. There are people who only use strum_macros because they don't need the traits that strum defines.

**Comment by Peternator7** [comment]
If this isn't doable though, I'd also be happy with the primary documentation being in the strum crate and `strum_macros` linking to the main docs. Not ideal, but better than nothing and duplicating the docs everywhere.

**Comment by jplatte** [comment]
It's definitely doable, I hadn't thought of the possibility of using strum_macros without strum. Usually re-exported macros are basically only in a separate crate because proc-macro items *can't be* in the same crate as regular library items :)

**Comment by Peternator7** [comment]
Updated version is on [crates](https://docs.rs/strum/0.19.5/strum/index.html). Thank you both so much for the help on this!
