### ISSUE TITLE
ToString: implement `Display`, std doc says "`ToString` shouldn't be implemented directly"

### ISSUE THREAD

**Issue by lo48576** [Peternator7/strum#12]
[Rustdoc for `ToString`](https://doc.rust-lang.org/std/string/trait.ToString.html) says:
> `ToString` shouldn't be implemented directly: `Display` should be implemented instead, and you get the `ToString` implementation for free.

So `derive(ToString)` should implement `std::fmt::Display` instead of `std::string::ToString` (and by this, `std::string::ToString` would be automatically implemented).
Then `derive(Display)` or some other appropriate names would be preferable to `derive(ToString)`.

This may be breaking changes (possibly rename `ToString` and `to_string`), but automatic derive for `Display` will be very useful.

**Comment by Peternator7** [comment]
Good catch! Since `ToString` already exists, I'm inclined to leave it and maintain backwards compatability, and then add an additional `derive(Display)` method as well.

That way we don't break existing code, and I can add a note on `ToString` that recommends using `Display` in most cases. I'll try and get to this soon :)

**Comment by Peternator7** [comment]
I have implemented this. I'll try and get it deployed soon.
