### ISSUE TITLE
EnumProperty Keep/Rename/Remove

### ISSUE THREAD

**Issue by Peternator7** [Peternator7/strum#129]
Evaluating the naming scheme and value of all the macros used in strum. Some are more or less redundant such as `ToString` now that `Display` exists. 

This is a tracking issue to solicit feedback about the usefulness of `EnumProperty` and whether it should be kept and if so, what it's name should be.

**Comment by linclelinkpart5** [comment]
Similar to `EnumProperty` for me, I don't see myself using this very much. Maybe if it were possible to enforce a property being defined for every variant (so that `Option` wasn't required), I would have more use for it. The real limiting factor for me is that I'd often want this for return values that are heap-allocated and not just `&'static str`/`usize`/`bool`.

**Comment by ronaldslc** [comment]
this is useful and exactly what I was looking for, I have a use case to attach event subjects to event enums
