### ISSUE TITLE
Case-insensitive `EnumString`?

### ISSUE THREAD

**Issue by ChayimFriedman2** [Peternator7/strum#154]
The title pretty much explains... I want to be able to convert string to enum without considering letter's case.

I'll be happy to work on PR once this is approved.

Things for consideration:

 - Do we want to support applying the attribute (say, `#[strum(case_insensitive)]`) to single variants too, or only to the whole enum?
 - Should we consider Unicode too? Variant names are ASCII, obviously, but aliases may be any string. Note that if we want Unicode this almost forces us to use an external library, such as [`unicase`](https://crates.io/crates/unicase).

**Comment by Peternator7** [comment]
This makes sense to me. Let's say it's approved in principal.

Here would be my inclinations:
- Unicode support would be great, but I'm hesitant to take a dependency to accomplish it. Coordinating MSRV's is annoying when this package doesn't change very frequently, but it's dependency does.
  - Longer term, maybe strum exposes an attribute to override the default equality function with a custom one which would let consumers do fancy unicode things.
- What happens if 2 variants differ only in case? The reasonable thing to do is just return the first one. We should just document that.
- This probably changes the match arms. We could either make it an if/else chain or something like this to keep the structure that we already use.
   ```rust
   match value {
        _ if value.insensitive_equals("Variant") => Ok(Enum::Variant)
        _ if value.insensitive_equals("OtherVar") => Ok(Enum::OtherVar)
        _ => Err(..)
   }
   ```

**Comment by ChayimFriedman2** [comment]
> Unicode support would be great, but I'm hesitant to take a dependency to accomplish it. Coordinating MSRV's is annoying when this package doesn't change very frequently, but it's dependency does.
Longer term, maybe strum exposes an attribute to override the default equality function with a custom one which would let consumers do fancy unicode things.

I think as a start, we may hide Unicode support behind a feature flag.

> What happens if 2 variants differ only in case? The reasonable thing to do is just return the first one. We should just document that.

I tend towards making it a compile error.

> This probably changes the match arms. We could either make it an if/else chain or something like this to keep the structure that we already use.

Yup. BTW, Rust already has a method for ASCII case-insensitive string equality: [`str.eq_ignore_ascii_case`](https://doc.rust-lang.org/std/primitive.str.html#method.eq_ignore_ascii_case).

**Comment by Peternator7** [comment]
Let's focus on ascii casing with the initial implementation and call it `ascii_case_insensitive` so it's clear what the flag does, and I'll get strum to expose a custom string comparer option in the future. That way someone could include full unicode support in the future and choose their own unicode library.

Will happily take a PR if you're still willing to work on this.
