### ISSUE TITLE
EnumProperty other than String?

### ISSUE THREAD

**Issue by Boscop** [Peternator7/strum#17]
When will it be possible to use `EnumProperty` with other types than String?
Are only literals supported or full expressions? :)

**Comment by Peternator7** [comment]
For a while, this was blocked because literals other than strings were experimental in the rust compiler. I'm not sure what the current status is. If other literal types have been stabilized, then this could be implemented. Is that something you would be interested in helping with?

I'd also say let's start with literals and then we can work towards full expressions. Currently only literals are supported in attributes.

**Comment by Boscop** [comment]
> EnumProperty: Enables the encoding of arbitary constants into enum variants. This method currently only supports adding additional string values. Other types of literals are still experimental in the rustc compiler.

Can't it be done the same way that the crates `smart-default` and `derive-new` support other types of values parsed from attribute strings: By just inlining the expr inside the quotes, instead of with the quotes.

**Comment by ZacJW** [comment]
I've written a crate, [associated-derive](https://crates.io/crates/associated-derive), that does something like what you're looking for. Not sure exactly how it would fit into strum. Do you have a syntax in mind?
