### ISSUE TITLE
Making EnumIter::get() a const fn

### ISSUE THREAD

**Issue by drewkett** [Peternator7/strum#179]
Would you have any interest in exposing the lookup by index that occurs in generated `get(idx)` implementation from `EnumIter` as a standalone `const fn`? I was working on making more code `const` in something I'm working on, and I was using `VARIANTS` from `EnumVariantNames` successfully. Then I wanted to be able to loop through the variants themselves and not just the `str` representations. I found that if I made the `get(idx)` method generated by `EnumIter` const , I could loop through the variants in `const` code as well using indices. I can make a simple PR to change the macro to mark that one method as const^, and then just use it as an undocumented feature of the code. Alternatively, I didn't know if you had any interest in exposing that functionality as a documented feature of `strum::EnumIter`. That said if this is something you don't want to support in `strum` I understand. 

%In order to do this I also had to change the definition from a method `fn (&self, idx: usize)` to an associated function `const fn(idx: usize)` since there is no way to create the Iter struct in const code right now, but it's not needed for `get` anyway

**Comment by Peternator7** [comment]
Hey @drewkett, yup, that sounds like a good fit for strum. I will happily take a PR if you submit one :)

**Comment by drewkett** [comment]
I just took a quick look. Do you think it makes more sense to make a separate macro for just the const get, which would mostly be a duplicate of the code from EnumIter without the unnecessary parts? (And then maybe refactor EnumIter to use that code?) Or just mark `EnumIter::get` as `const` and document it?

**Comment by drewkett** [comment]
`std::ops::Index` uses the method name `index`. So maybe `const_index`? Can't imagine that would conflict with much for must enums. Then we could name the macro `EnumConstIndex` for consistency

**Comment by Fuuzetsu** [comment]
I'd like to ask to re-open this ticket. It appears that it was closed because `FromRepr` now exists. That's _also_ useful but separate to what `EnumIter::get()` lets you do. With `EnumIter::get()`, the underlying representation doesn't matter.

A simple use-case is to iterate over all the variants in constant context. Given `EnumCount` and some kind of `const fn get(idx: usize) -> T`, it becomes possible to iterate over all the variants. Currently, with just `FromRepr`, I think it's still not doable because even though you might know that you have 25 variants, they aren't necessarily available by just `FromRepr`ing the values from `0..25`.

**Comment by Fuuzetsu** [comment]
PS: It doesn't have to be specifically `EnumIter::get()`. It can be a new trait or a method or a stand-alone function, whatever works.
