### ISSUE TITLE
Documentation for `VariantArray` and `VariantNames` say their `VARIANTS` constants are arrays, but they're actually slices

### ISSUE THREAD

**Issue by IndigoLily** [Peternator7/strum#335]
The incorrect documentation:

https://github.com/Peternator7/strum/blob/2056939963527cc89f192239cb3c0262467ddb9d/strum_macros/src/lib.rs#L169

https://github.com/Peternator7/strum/blob/2056939963527cc89f192239cb3c0262467ddb9d/strum_macros/src/lib.rs#L215

https://github.com/Peternator7/strum/blob/2056939963527cc89f192239cb3c0262467ddb9d/strum/src/lib.rs#L220

The actual types:

https://github.com/Peternator7/strum/blob/2056939963527cc89f192239cb3c0262467ddb9d/strum/src/lib.rs#L217

https://github.com/Peternator7/strum/blob/2056939963527cc89f192239cb3c0262467ddb9d/strum/src/lib.rs#L227

I personally think these constants should be actual arrays (because it's much easier to get a slice from an array than vice versa), but I'm not sure how feasible that is in current stable Rust.

**Comment by T0mstone** [comment]
Wow, I was about to write the same issue. What a coincidence!

You're right, making them true arrays won't work yet, since associated types aren't allowed to depend on associated constants. A workaround would be to make the array length a generic parameter of the trait, but that's pretty unwieldy, in addition to being semantically completely wrong.

I would be in favor of the macros also generating an inherent associated constant which is a true array. That way we can at least use the constant length in non-generic code.

**Comment by Peternator7** [comment]
There was discussion when the features were added about slices vs arrays. Like @T0mstone said, associated constants still aren't great to use. It also makes adding a new variant to an enum a breaking change because the length of the array changes, but slices don't have that issue.

**Comment by asasine** [comment]
Unfortunately, since the name of the derive and trait is `VariantArray`, I think this users are destined to continue falling for this.

Regarding the breaking change from the length of the array changing and supposing `VariantArray` actually created an array, could we lean on [`non_exhaustive`](https://doc.rust-lang.org/reference/attributes/type_system.html#the-non_exhaustive-attribute) attribute here? If the enum is exhaustive, it's already a breaking change to add a variant, so the fact that the associated array constant changes lenght is fine. For an enum that is not exhaustive, we could prevent using `VariantArray` and instead suggest `VariantStaticSlice`.
