### ISSUE TITLE
v0.14.0 missing from changelog

### ISSUE THREAD

**Issue by Turbo87** [Peternator7/strum#45]
This project does have a `CHANGELOG.md` file (👏), but it seems like the new v0.14.0 release is missing from it. What were the changes that went into that release? Were there any breaking changes?

**Comment by Peternator7** [comment]
Good catch. #42 and #43 were fixed in 0.14.0.

#42 fixed an issue where several of the derives were ignoring the `serialize_all` attribute so the behavior may have changed if you were using those derives and `serialize_all` on the same enum, but it was incorrect behavior. I'm working on a fix for another issue so I'll update the changelog with both deployments when I get that deployed.
