### ISSUE TITLE
Help with 2018 edition

### ISSUE THREAD

**Issue by bestouff** [Peternator7/strum#47]
Using strum with rust 2018 probably needs a `use strum<something>::strum;` because by default this error appears:
```
error[E0658]: The attribute `strum` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
 --> /home/xav/lfgt/target/debug/build/lfgt-3925bf91df78c23d/out/equipments.rs:3:5
  |
3 |     #[strum(serialize = "agt")]
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Would it be possible to add the remedy to the README.md ?

**Comment by Peternator7** [comment]
You'll typically get this error if you haven't added a `#[derive(...)]` to the enum yet. Each of strum's custom derives tell the compiler that they know how to interpret `#[strum(...)]` on an attribute. Otherwise it's an error like you're seeing.

Let me know if adding a derive such as 
```
use strum_macros::EnumString;

#[derive(EnumString)]
enum A {
    #[strum(serialize = "agt")]
    MyVariant
}
```

fixes the issue.

**Comment by bestouff** [comment]
Indeed that was it, thanks ! I had a hard time spotting this, I'm generating code in a build.rs. The error message wasn't very explicit.
