### ISSUE TITLE
IntoEnumIterator: consider using standard IntoIterator instead

### ISSUE THREAD

**Issue by lucab** [Peternator7/strum#5]
It would be nice if strum could incapsulate a bit more its implementation details.

In particular, I'd like to avoid having `strum::IntoEnumIterator` to be imported by all consumers, and instead use the `IntoIterator` one from stdlib.
That one however is a consuming method, so I'm not sure if it can be transparently adopted. An alternative would be to drop the trait completely and just expose a naked `iter()` like most collection types do.

**Comment by Peternator7** [comment]
Hey @lucab,

Thanks for the feedback! Unfortunately, like you said, `IntoIterator` doesn't have the same signature as `IntoEnumIterator` so I can't simply implement that trait.

Regarding the trait, it's a more philosophical design decision than anything. Since these functions are being automatically implemented, it seems like a good practice to me to hide them behind traits that way someone can ignore them if they aren't interested. It also let's you abstract over the trait which is nice :) 

While not a perfect solution, if you want to hide the trait from the consumers, you can do something like this:

```
impl YourEnum {
    fn iter() -> YourEnumIter {
        <Self as IntoEnumIter>::iter()
    }
}
```

Then your consumers won't need to import the trait to use the function.

**Comment by lucab** [comment]
Thanks for your comment. I understand the logic behind using traits, I'm fine with that approach but I'm trying to see how a "library using strum" can better decouple its consumers from strum (otherwise there are multiple strum dependencies to be sparkled across different projects and to be kept updated in sync). This also affect `strum::ParseError` in a similar way.

The options I was thinking about, but I haven't yet tried are:
 * re-exporting strum traits in my own crates and let the public derives refer to them (I'm not even sure if feasible)
 * (only for the iterator case) implement a separate `IntoIterator` using the trait from stdlib
 * having some visibility control knob, so strum traits don't end up exposed by default just because the enum is public

> While not a perfect solution, if you want to hide the trait from the consumers, you can do something like this:

Right, I can further incapsulate myself but this still results in exposed trait methods from a different crate. I'm not much concerned with having trait involved, but with having strum details exposed to consumers of my strum-using library.

Related, I will probably follow up with similar considerations for `ParseError` after a bit of due diligence, but I think that can be easily solved via [error-chaining](https://docs.rs/error-chain).

**Comment by Peternator7** [comment]
I am still thinking about this. Strum derives the trait using the absolute path by design. This works better in the general case, and avoids numerous compiler errors. You could certainly fork it and have it derive a different implementation for you.

Ideally, Strum would accept an optional parameter to implement a different trait or implement the methods directly on the struct. Unfortunately, the syntax below doesn't seem to be allowed on custom derives at the moment.

```
// illegal syntax
#[EnumIter(derive_trait="::my::special::Trait")]
enum Color {
    Red,
    Blue,
}
```
