### ISSUE TITLE
Convert isize to enum variant

### ISSUE THREAD

**Issue by Nugine** [Peternator7/strum#52]
Sometimes we need to convert `isize` to an enum variant with explicit discriminator.
[enum/c_like](https://doc.rust-lang.org/rust-by-example/custom_types/enum/c_like.html)
For example, high level API converts error code to an error enum variant. The feature will be useful when it comes to unsafe and FFI.

The solution is to implement a proc macro like:
`proc_macro_derive(EnumFromIsize)`

The generated code will look like:
```rust
impl TryFrom<isize> for MyEnum {
    type Error = StrumCustomError;
    fn try_from(u: isize) -> Result<MyEnum, StrumCustomError> {
        match u {
            // ......
        }
    }
}
```

**Comment by Peternator7** [comment]
Thanks for opening the issue @Nugine! This makes a lot of sense to me. Take a peek at [this answer](https://stackoverflow.com/a/28029279) on SO that links to the num-derive crate. It might do everything you need it to. 

I'm not opposed to Strum doing this either, but I imagine the implementations will be nearly identical.

**Comment by Nugine** [comment]
`num-derive` is what I need. Thank you!
